/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class AgentPoolLocator {
    'agent'?: string;
    'id'?: string;
    'item'?: string;
    'name'?: string;
    'project'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "agent",
            "baseName": "agent",
            "type": "string",
            "format": "AgentLocator"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "string",
            "format": "item:(&lt;locator1&gt;),item:(&lt;locator2&gt;...)"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "string",
            "format": "ProjectLocator"
        }    ];

    static getAttributeTypeMap() {
        return AgentPoolLocator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

