/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Agents } from './Agents.ts';
import { Project } from './Project.ts';
import { Projects } from './Projects.ts';
import { HttpFile } from '../http/http.ts';

export class AgentPool {
    'id'?: number;
    'name'?: string;
    'href'?: string;
    'maxAgents'?: number;
    'ownerProject'?: Project;
    'projects'?: Projects;
    'agents'?: Agents;
    'locator'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "maxAgents",
            "baseName": "maxAgents",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "ownerProject",
            "baseName": "ownerProject",
            "type": "Project",
            "format": ""
        },
        {
            "name": "projects",
            "baseName": "projects",
            "type": "Projects",
            "format": ""
        },
        {
            "name": "agents",
            "baseName": "agents",
            "type": "Agents",
            "format": ""
        },
        {
            "name": "locator",
            "baseName": "locator",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AgentPool.attributeTypeMap;
    }
    
    public constructor() {
    }
}

