/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class AgentLocator {
    'authorized'?: boolean;
    'build'?: string;
    'compatible'?: string;
    'connected'?: boolean;
    'count'?: number;
    'enabled'?: boolean;
    'id'?: number;
    'ip'?: string;
    'item'?: string;
    'name'?: string;
    'parameter'?: string;
    'pool'?: string;
    'start'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "authorized",
            "baseName": "authorized",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "string",
            "format": "BuildLocator"
        },
        {
            "name": "compatible",
            "baseName": "compatible",
            "type": "string",
            "format": "BuildTypeLocator"
        },
        {
            "name": "connected",
            "baseName": "connected",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "ip",
            "baseName": "ip",
            "type": "string",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "string",
            "format": "item:(&lt;locator1&gt;),item:(&lt;locator2&gt;...)"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "parameter",
            "baseName": "parameter",
            "type": "string",
            "format": ""
        },
        {
            "name": "pool",
            "baseName": "pool",
            "type": "string",
            "format": "AgentPoolLocator"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": "int32"
        }    ];

    static getAttributeTypeMap() {
        return AgentLocator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

