/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class BranchLocator {
    'branched'?: boolean;
    'build'?: string;
    'buildType'?: string;
    '_default'?: boolean;
    'item'?: string;
    'name'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "branched",
            "baseName": "branched",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "string",
            "format": "BuildLocator"
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "string",
            "format": "BuildTypeLocator"
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean",
            "format": "boolean"
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "string",
            "format": "item:(&lt;locator1&gt;),item:(&lt;locator2&gt;...)"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BranchLocator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

