/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Builds } from './Builds.ts';
import { HttpFile } from '../http/http.ts';

export class BranchVersion {
    'version'?: string;
    'unspecified'?: boolean;
    'lastActivity'?: string;
    'groupFlag'?: boolean;
    'builds'?: Builds;
    'internalName'?: string;
    'name'?: string;
    '_default'?: boolean;
    'active'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "unspecified",
            "baseName": "unspecified",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastActivity",
            "baseName": "lastActivity",
            "type": "string",
            "format": ""
        },
        {
            "name": "groupFlag",
            "baseName": "groupFlag",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "builds",
            "baseName": "builds",
            "type": "Builds",
            "format": ""
        },
        {
            "name": "internalName",
            "baseName": "internalName",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "_default",
            "baseName": "default",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BranchVersion.attributeTypeMap;
    }
    
    public constructor() {
    }
}

