/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Agent } from './Agent.ts';
import { Agents } from './Agents.ts';
import { ArtifactDependencies } from './ArtifactDependencies.ts';
import { BuildChanges } from './BuildChanges.ts';
import { BuildTriggeringOptions } from './BuildTriggeringOptions.ts';
import { BuildType } from './BuildType.ts';
import { Builds } from './Builds.ts';
import { Changes } from './Changes.ts';
import { Comment } from './Comment.ts';
import { Customizations } from './Customizations.ts';
import { Datas } from './Datas.ts';
import { Entries } from './Entries.ts';
import { Files } from './Files.ts';
import { IssuesUsages } from './IssuesUsages.ts';
import { Items } from './Items.ts';
import { Links } from './Links.ts';
import { ProblemOccurrences } from './ProblemOccurrences.ts';
import { ProgressInfo } from './ProgressInfo.ts';
import { Properties } from './Properties.ts';
import { Related } from './Related.ts';
import { Revision } from './Revision.ts';
import { Revisions } from './Revisions.ts';
import { Tags } from './Tags.ts';
import { TestOccurrences } from './TestOccurrences.ts';
import { TriggeredBy } from './TriggeredBy.ts';
import { User } from './User.ts';
import { VcsLabel } from './VcsLabel.ts';
import { HttpFile } from '../http/http.ts';

export class Build {
    'id'?: number;
    'taskId'?: number;
    'buildTypeId'?: string;
    'buildTypeInternalId'?: string;
    'number'?: string;
    'status'?: string;
    'state'?: string;
    'running'?: boolean;
    'composite'?: boolean;
    'failedToStart'?: boolean;
    'personal'?: boolean;
    'percentageComplete'?: number;
    'branchName'?: string;
    'defaultBranch'?: boolean;
    'unspecifiedBranch'?: boolean;
    'history'?: boolean;
    'pinned'?: boolean;
    'href'?: string;
    'webUrl'?: string;
    'queuePosition'?: number;
    'limitedChangesCount'?: number;
    'artifactsDirectory'?: string;
    'links'?: Links;
    'statusText'?: string;
    'buildType'?: BuildType;
    'comment'?: Comment;
    'tags'?: Tags;
    'pinInfo'?: Comment;
    'user'?: User;
    'startEstimate'?: string;
    'waitReason'?: string;
    'finishEstimate'?: string;
    'runningInfo'?: ProgressInfo;
    'canceledInfo'?: Comment;
    'queuedDate'?: string;
    'startDate'?: string;
    'finishDate'?: string;
    'triggered'?: TriggeredBy;
    'lastChanges'?: Changes;
    'changes'?: Changes;
    'revisions'?: Revisions;
    'versionedSettingsRevision'?: Revision;
    'artifactDependencyChanges'?: BuildChanges;
    'agent'?: Agent;
    'compatibleAgents'?: Agents;
    'testOccurrences'?: TestOccurrences;
    'problemOccurrences'?: ProblemOccurrences;
    'artifacts'?: Files;
    'relatedIssues'?: IssuesUsages;
    'properties'?: Properties;
    'resultingProperties'?: Properties;
    'attributes'?: Entries;
    'statistics'?: Properties;
    'metadata'?: Datas;
    'snapshotDependencies'?: Builds;
    'artifactDependencies'?: Builds;
    'customArtifactDependencies'?: ArtifactDependencies;
    'settingsHash'?: string;
    'currentSettingsHash'?: string;
    'modificationId'?: string;
    'chainModificationId'?: string;
    'replacementIds'?: Items;
    'related'?: Related;
    'triggeringOptions'?: BuildTriggeringOptions;
    'usedByOtherBuilds'?: boolean;
    'statusChangeComment'?: Comment;
    'vcsLabels'?: Array<VcsLabel>;
    'detachedFromAgent'?: boolean;
    'finishOnAgentDate'?: string;
    'customized'?: boolean;
    'customization'?: Customizations;
    'locator'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "taskId",
            "baseName": "taskId",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "buildTypeId",
            "baseName": "buildTypeId",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildTypeInternalId",
            "baseName": "buildTypeInternalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "running",
            "baseName": "running",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "composite",
            "baseName": "composite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "failedToStart",
            "baseName": "failedToStart",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "personal",
            "baseName": "personal",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "percentageComplete",
            "baseName": "percentageComplete",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "branchName",
            "baseName": "branchName",
            "type": "string",
            "format": ""
        },
        {
            "name": "defaultBranch",
            "baseName": "defaultBranch",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "unspecifiedBranch",
            "baseName": "unspecifiedBranch",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "history",
            "baseName": "history",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "pinned",
            "baseName": "pinned",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "webUrl",
            "baseName": "webUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "queuePosition",
            "baseName": "queuePosition",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "limitedChangesCount",
            "baseName": "limitedChangesCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "artifactsDirectory",
            "baseName": "artifactsDirectory",
            "type": "string",
            "format": ""
        },
        {
            "name": "links",
            "baseName": "links",
            "type": "Links",
            "format": ""
        },
        {
            "name": "statusText",
            "baseName": "statusText",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "BuildType",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "Comment",
            "format": ""
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "Tags",
            "format": ""
        },
        {
            "name": "pinInfo",
            "baseName": "pinInfo",
            "type": "Comment",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "User",
            "format": ""
        },
        {
            "name": "startEstimate",
            "baseName": "startEstimate",
            "type": "string",
            "format": ""
        },
        {
            "name": "waitReason",
            "baseName": "waitReason",
            "type": "string",
            "format": ""
        },
        {
            "name": "finishEstimate",
            "baseName": "finishEstimate",
            "type": "string",
            "format": ""
        },
        {
            "name": "runningInfo",
            "baseName": "running-info",
            "type": "ProgressInfo",
            "format": ""
        },
        {
            "name": "canceledInfo",
            "baseName": "canceledInfo",
            "type": "Comment",
            "format": ""
        },
        {
            "name": "queuedDate",
            "baseName": "queuedDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "finishDate",
            "baseName": "finishDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "triggered",
            "baseName": "triggered",
            "type": "TriggeredBy",
            "format": ""
        },
        {
            "name": "lastChanges",
            "baseName": "lastChanges",
            "type": "Changes",
            "format": ""
        },
        {
            "name": "changes",
            "baseName": "changes",
            "type": "Changes",
            "format": ""
        },
        {
            "name": "revisions",
            "baseName": "revisions",
            "type": "Revisions",
            "format": ""
        },
        {
            "name": "versionedSettingsRevision",
            "baseName": "versionedSettingsRevision",
            "type": "Revision",
            "format": ""
        },
        {
            "name": "artifactDependencyChanges",
            "baseName": "artifactDependencyChanges",
            "type": "BuildChanges",
            "format": ""
        },
        {
            "name": "agent",
            "baseName": "agent",
            "type": "Agent",
            "format": ""
        },
        {
            "name": "compatibleAgents",
            "baseName": "compatibleAgents",
            "type": "Agents",
            "format": ""
        },
        {
            "name": "testOccurrences",
            "baseName": "testOccurrences",
            "type": "TestOccurrences",
            "format": ""
        },
        {
            "name": "problemOccurrences",
            "baseName": "problemOccurrences",
            "type": "ProblemOccurrences",
            "format": ""
        },
        {
            "name": "artifacts",
            "baseName": "artifacts",
            "type": "Files",
            "format": ""
        },
        {
            "name": "relatedIssues",
            "baseName": "relatedIssues",
            "type": "IssuesUsages",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Properties",
            "format": ""
        },
        {
            "name": "resultingProperties",
            "baseName": "resultingProperties",
            "type": "Properties",
            "format": ""
        },
        {
            "name": "attributes",
            "baseName": "attributes",
            "type": "Entries",
            "format": ""
        },
        {
            "name": "statistics",
            "baseName": "statistics",
            "type": "Properties",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "Datas",
            "format": ""
        },
        {
            "name": "snapshotDependencies",
            "baseName": "snapshot-dependencies",
            "type": "Builds",
            "format": ""
        },
        {
            "name": "artifactDependencies",
            "baseName": "artifact-dependencies",
            "type": "Builds",
            "format": ""
        },
        {
            "name": "customArtifactDependencies",
            "baseName": "custom-artifact-dependencies",
            "type": "ArtifactDependencies",
            "format": ""
        },
        {
            "name": "settingsHash",
            "baseName": "settingsHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "currentSettingsHash",
            "baseName": "currentSettingsHash",
            "type": "string",
            "format": ""
        },
        {
            "name": "modificationId",
            "baseName": "modificationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "chainModificationId",
            "baseName": "chainModificationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "replacementIds",
            "baseName": "replacementIds",
            "type": "Items",
            "format": ""
        },
        {
            "name": "related",
            "baseName": "related",
            "type": "Related",
            "format": ""
        },
        {
            "name": "triggeringOptions",
            "baseName": "triggeringOptions",
            "type": "BuildTriggeringOptions",
            "format": ""
        },
        {
            "name": "usedByOtherBuilds",
            "baseName": "usedByOtherBuilds",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "statusChangeComment",
            "baseName": "statusChangeComment",
            "type": "Comment",
            "format": ""
        },
        {
            "name": "vcsLabels",
            "baseName": "vcsLabels",
            "type": "Array<VcsLabel>",
            "format": ""
        },
        {
            "name": "detachedFromAgent",
            "baseName": "detachedFromAgent",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "finishOnAgentDate",
            "baseName": "finishOnAgentDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "customized",
            "baseName": "customized",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "customization",
            "baseName": "customization",
            "type": "Customizations",
            "format": ""
        },
        {
            "name": "locator",
            "baseName": "locator",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Build.attributeTypeMap;
    }
    
    public constructor() {
    }
}

