/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BuildType } from './BuildType.ts';
import { HttpFile } from '../http/http.ts';

export class BuildTypes {
    'count'?: number;
    'href'?: string;
    'nextHref'?: string;
    'prevHref'?: string;
    'buildType'?: Array<BuildType>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "nextHref",
            "baseName": "nextHref",
            "type": "string",
            "format": ""
        },
        {
            "name": "prevHref",
            "baseName": "prevHref",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "Array<BuildType>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BuildTypes.attributeTypeMap;
    }
    
    public constructor() {
    }
}

