/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class BuildCancelRequest {
    'comment'?: string;
    'readdIntoQueue'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "readdIntoQueue",
            "baseName": "readdIntoQueue",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BuildCancelRequest.attributeTypeMap;
    }
    
    public constructor() {
    }
}

