/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BuildTypes } from './BuildTypes.ts';
import { HttpFile } from '../http/http.ts';

export class BuildTriggeringOptions {
    'cleanSources'?: boolean;
    'cleanSourcesInAllDependencies'?: boolean;
    'rebuildAllDependencies'?: boolean;
    'rebuildFailedOrIncompleteDependencies'?: boolean;
    'queueAtTop'?: boolean;
    'freezeSettings'?: boolean;
    'tagDependencies'?: boolean;
    'rebuildDependencies'?: BuildTypes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "cleanSources",
            "baseName": "cleanSources",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "cleanSourcesInAllDependencies",
            "baseName": "cleanSourcesInAllDependencies",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rebuildAllDependencies",
            "baseName": "rebuildAllDependencies",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rebuildFailedOrIncompleteDependencies",
            "baseName": "rebuildFailedOrIncompleteDependencies",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "queueAtTop",
            "baseName": "queueAtTop",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "freezeSettings",
            "baseName": "freezeSettings",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "tagDependencies",
            "baseName": "tagDependencies",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "rebuildDependencies",
            "baseName": "rebuildDependencies",
            "type": "BuildTypes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BuildTriggeringOptions.attributeTypeMap;
    }
    
    public constructor() {
    }
}

