/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class BuildLocator {
    'affectedProject'?: string;
    'agent'?: string;
    'agentTypeId'?: number;
    'any'?: boolean;
    'artifactDependency'?: string;
    'branch'?: string;
    'buildType'?: string;
    'canceled'?: boolean;
    'compatibleAgent'?: string;
    'composite'?: boolean;
    'count'?: number;
    'defaultFilter'?: boolean;
    'failedToStart'?: boolean;
    'finishDate'?: string;
    'finished'?: boolean;
    'hanging'?: boolean;
    'history'?: boolean;
    'id'?: number;
    'item'?: string;
    'lookupLimit'?: number;
    'number'?: string;
    'personal'?: boolean;
    'pinned'?: boolean;
    'project'?: string;
    'property'?: string;
    'queued'?: boolean;
    'queuedDate'?: string;
    'running'?: boolean;
    'snapshotDependency'?: string;
    'start'?: number;
    'startDate'?: string;
    'state'?: string;
    'status'?: string;
    'tag'?: string;
    'taskId'?: number;
    'user'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "affectedProject",
            "baseName": "affectedProject",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "agent",
            "baseName": "agent",
            "type": "string",
            "format": "AgentLocator"
        },
        {
            "name": "agentTypeId",
            "baseName": "agentTypeId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "any",
            "baseName": "any",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "artifactDependency",
            "baseName": "artifactDependency",
            "type": "string",
            "format": ""
        },
        {
            "name": "branch",
            "baseName": "branch",
            "type": "string",
            "format": "BranchLocator"
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "string",
            "format": "BuildTypeLocator"
        },
        {
            "name": "canceled",
            "baseName": "canceled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "compatibleAgent",
            "baseName": "compatibleAgent",
            "type": "string",
            "format": "AgentLocator"
        },
        {
            "name": "composite",
            "baseName": "composite",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "defaultFilter",
            "baseName": "defaultFilter",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "failedToStart",
            "baseName": "failedToStart",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "finishDate",
            "baseName": "finishDate",
            "type": "string",
            "format": "date:&lt;yyyyMMddTHHmmss+ZZZZ&gt;,build:&lt;build locator&gt;,condition:&lt;before/after&gt;"
        },
        {
            "name": "finished",
            "baseName": "finished",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "hanging",
            "baseName": "hanging",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "history",
            "baseName": "history",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "string",
            "format": "item:(&lt;locator1&gt;),item:(&lt;locator2&gt;...)"
        },
        {
            "name": "lookupLimit",
            "baseName": "lookupLimit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "personal",
            "baseName": "personal",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "pinned",
            "baseName": "pinned",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string",
            "format": "property:(name:&lt;name&gt;,value:&lt;value&gt;,matchType:&lt;matchType&gt;)"
        },
        {
            "name": "queued",
            "baseName": "queued",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "queuedDate",
            "baseName": "queuedDate",
            "type": "string",
            "format": "date:&lt;yyyyMMddTHHmmss+ZZZZ&gt;,build:&lt;build locator&gt;,condition:&lt;before/after&gt;"
        },
        {
            "name": "running",
            "baseName": "running",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "snapshotDependency",
            "baseName": "snapshotDependency",
            "type": "string",
            "format": ""
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string",
            "format": "date:&lt;yyyyMMddTHHmmss+ZZZZ&gt;,build:&lt;build locator&gt;,condition:&lt;before/after&gt;"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "tag",
            "baseName": "tag",
            "type": "string",
            "format": "TagLocator"
        },
        {
            "name": "taskId",
            "baseName": "taskId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": "UserLocator"
        }    ];

    static getAttributeTypeMap() {
        return BuildLocator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

