/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class ChangeLocator {
    'build'?: string;
    'buildType'?: string;
    'comment'?: string;
    'count'?: number;
    'file'?: string;
    'id'?: number;
    'internalVersion'?: string;
    'item'?: string;
    'pending'?: boolean;
    'project'?: string;
    'sinceChange'?: string;
    'start'?: number;
    'user'?: string;
    'username'?: string;
    'vcsRoot'?: string;
    'vcsRootInstance'?: string;
    'version'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "build",
            "baseName": "build",
            "type": "string",
            "format": "BuildLocator"
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "string",
            "format": "BuildTypeLocator"
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "internalVersion",
            "baseName": "internalVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "string",
            "format": "item:(&lt;locator1&gt;),item:(&lt;locator2&gt;...)"
        },
        {
            "name": "pending",
            "baseName": "pending",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "sinceChange",
            "baseName": "sinceChange",
            "type": "string",
            "format": ""
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "string",
            "format": "UserLocator"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "vcsRoot",
            "baseName": "vcsRoot",
            "type": "string",
            "format": "VcsRootLocator"
        },
        {
            "name": "vcsRootInstance",
            "baseName": "vcsRootInstance",
            "type": "string",
            "format": "VcsRootInstanceLocator"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChangeLocator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

