/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Agent } from './Agent.ts';
import { CloudImage } from './CloudImage.ts';
import { HttpFile } from '../http/http.ts';

export class CloudInstance {
    'id'?: string;
    'name'?: string;
    'state'?: string;
    'startDate'?: string;
    'networkAddress'?: string;
    'href'?: string;
    'image'?: CloudImage;
    'agent'?: Agent;
    'errorMessage'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "startDate",
            "baseName": "startDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "networkAddress",
            "baseName": "networkAddress",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "CloudImage",
            "format": ""
        },
        {
            "name": "agent",
            "baseName": "agent",
            "type": "Agent",
            "format": ""
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CloudInstance.attributeTypeMap;
    }
    
    public constructor() {
    }
}

