/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CloudProfile } from './CloudProfile.ts';
import { HttpFile } from '../http/http.ts';

export class CloudProfiles {
    'count'?: number;
    'nextHref'?: string;
    'prevHref'?: string;
    'href'?: string;
    'cloudProfile'?: Array<CloudProfile>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "nextHref",
            "baseName": "nextHref",
            "type": "string",
            "format": ""
        },
        {
            "name": "prevHref",
            "baseName": "prevHref",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "cloudProfile",
            "baseName": "cloudProfile",
            "type": "Array<CloudProfile>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CloudProfiles.attributeTypeMap;
    }
    
    public constructor() {
    }
}

