/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { CloudInstances } from './CloudInstances.ts';
import { CloudProfile } from './CloudProfile.ts';
import { HttpFile } from '../http/http.ts';

export class CloudImage {
    'id'?: string;
    'name'?: string;
    'href'?: string;
    'profile'?: CloudProfile;
    'instances'?: CloudInstances;
    'errorMessage'?: string;
    'agentTypeId'?: number;
    'agentPoolId'?: number;
    'operatingSystemName'?: string;
    'locator'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "CloudProfile",
            "format": ""
        },
        {
            "name": "instances",
            "baseName": "instances",
            "type": "CloudInstances",
            "format": ""
        },
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "string",
            "format": ""
        },
        {
            "name": "agentTypeId",
            "baseName": "agentTypeId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "agentPoolId",
            "baseName": "agentPoolId",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "operatingSystemName",
            "baseName": "operatingSystemName",
            "type": "string",
            "format": ""
        },
        {
            "name": "locator",
            "baseName": "locator",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CloudImage.attributeTypeMap;
    }
    
    public constructor() {
    }
}

