/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Agent } from './Agent.ts';
import { BuildType } from './BuildType.ts';
import { Requirements } from './Requirements.ts';
import { HttpFile } from '../http/http.ts';

export class Compatibility {
    'compatible'?: boolean;
    'agent'?: Agent;
    'buildType'?: BuildType;
    'unmetRequirements'?: Requirements;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "compatible",
            "baseName": "compatible",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "agent",
            "baseName": "agent",
            "type": "Agent",
            "format": ""
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "BuildType",
            "format": ""
        },
        {
            "name": "unmetRequirements",
            "baseName": "unmetRequirements",
            "type": "Requirements",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Compatibility.attributeTypeMap;
    }
    
    public constructor() {
    }
}

