/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BuildTypes } from './BuildTypes.ts';
import { HttpFile } from '../http/http.ts';

export class CompatibilityPolicy {
    'policy'?: string;
    'buildTypes'?: BuildTypes;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "policy",
            "baseName": "policy",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildTypes",
            "baseName": "buildTypes",
            "type": "BuildTypes",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CompatibilityPolicy.attributeTypeMap;
    }
    
    public constructor() {
    }
}

