/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class FileChange {
    'beforeRevision'?: string;
    'afterRevision'?: string;
    'changeType'?: string;
    'changeTypeComment'?: string;
    'file'?: string;
    'relativeFile'?: string;
    'directory'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "beforeRevision",
            "baseName": "before-revision",
            "type": "string",
            "format": ""
        },
        {
            "name": "afterRevision",
            "baseName": "after-revision",
            "type": "string",
            "format": ""
        },
        {
            "name": "changeType",
            "baseName": "changeType",
            "type": "string",
            "format": ""
        },
        {
            "name": "changeTypeComment",
            "baseName": "changeTypeComment",
            "type": "string",
            "format": ""
        },
        {
            "name": "file",
            "baseName": "file",
            "type": "string",
            "format": ""
        },
        {
            "name": "relativeFile",
            "baseName": "relative-file",
            "type": "string",
            "format": ""
        },
        {
            "name": "directory",
            "baseName": "directory",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return FileChange.attributeTypeMap;
    }
    
    public constructor() {
    }
}

