/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Groups } from './Groups.ts';
import { Properties } from './Properties.ts';
import { Roles } from './Roles.ts';
import { Users } from './Users.ts';
import { HttpFile } from '../http/http.ts';

export class Group {
    'key'?: string;
    'name'?: string;
    'href'?: string;
    'description'?: string;
    'parentGroups'?: Groups;
    'childGroups'?: Groups;
    'users'?: Users;
    'roles'?: Roles;
    'properties'?: Properties;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "parentGroups",
            "baseName": "parent-groups",
            "type": "Groups",
            "format": ""
        },
        {
            "name": "childGroups",
            "baseName": "child-groups",
            "type": "Groups",
            "format": ""
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "Users",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Roles",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Properties",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Group.attributeTypeMap;
    }
    
    public constructor() {
    }
}

