/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class InvestigationLocator {
    'affectedProject'?: string;
    'assignee'?: string;
    'assignmentProject'?: string;
    'buildType'?: string;
    'count'?: number;
    'item'?: string;
    'lookupLimit'?: number;
    'problem'?: string;
    'reporter'?: string;
    'resolution'?: string;
    'sinceDate'?: Date;
    'start'?: number;
    'state'?: string;
    'test'?: string;
    'type'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "affectedProject",
            "baseName": "affectedProject",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "assignee",
            "baseName": "assignee",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignmentProject",
            "baseName": "assignmentProject",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "string",
            "format": "BuildTypeLocator"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "string",
            "format": "item:(&lt;locator1&gt;),item:(&lt;locator2&gt;...)"
        },
        {
            "name": "lookupLimit",
            "baseName": "lookupLimit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "problem",
            "baseName": "problem",
            "type": "string",
            "format": "ProblemLocator"
        },
        {
            "name": "reporter",
            "baseName": "reporter",
            "type": "string",
            "format": ""
        },
        {
            "name": "resolution",
            "baseName": "resolution",
            "type": "string",
            "format": ""
        },
        {
            "name": "sinceDate",
            "baseName": "sinceDate",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "string",
            "format": "TestLocator"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return InvestigationLocator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

