/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Comment } from './Comment.ts';
import { ProblemScope } from './ProblemScope.ts';
import { ProblemTarget } from './ProblemTarget.ts';
import { Resolution } from './Resolution.ts';
import { User } from './User.ts';
import { HttpFile } from '../http/http.ts';

export class Investigation {
    'id'?: string;
    'state'?: string;
    'href'?: string;
    'assignee'?: User;
    'assignment'?: Comment;
    'scope'?: ProblemScope;
    'target'?: ProblemTarget;
    'resolution'?: Resolution;
    'responsible'?: User;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "assignee",
            "baseName": "assignee",
            "type": "User",
            "format": ""
        },
        {
            "name": "assignment",
            "baseName": "assignment",
            "type": "Comment",
            "format": ""
        },
        {
            "name": "scope",
            "baseName": "scope",
            "type": "ProblemScope",
            "format": ""
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "ProblemTarget",
            "format": ""
        },
        {
            "name": "resolution",
            "baseName": "resolution",
            "type": "Resolution",
            "format": ""
        },
        {
            "name": "responsible",
            "baseName": "responsible",
            "type": "User",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Investigation.attributeTypeMap;
    }
    
    public constructor() {
    }
}

