/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Changes } from './Changes.ts';
import { Issue } from './Issue.ts';
import { HttpFile } from '../http/http.ts';

export class IssueUsage {
    'changes'?: Changes;
    'issue'?: Issue;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "changes",
            "baseName": "changes",
            "type": "Changes",
            "format": ""
        },
        {
            "name": "issue",
            "baseName": "issue",
            "type": "Issue",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return IssueUsage.attributeTypeMap;
    }
    
    public constructor() {
    }
}

