/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class LicenseKey {
    'valid'?: boolean;
    'active'?: boolean;
    'expired'?: boolean;
    'obsolete'?: boolean;
    'expirationDate'?: string;
    'maintenanceEndDate'?: string;
    'type'?: string;
    'servers'?: number;
    'agents'?: number;
    'unlimitedAgents'?: boolean;
    'buildTypes'?: number;
    'unlimitedBuildTypes'?: boolean;
    'errorDetails'?: string;
    'key'?: string;
    'rawType'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "valid",
            "baseName": "valid",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "active",
            "baseName": "active",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expired",
            "baseName": "expired",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "obsolete",
            "baseName": "obsolete",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "expirationDate",
            "baseName": "expirationDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "maintenanceEndDate",
            "baseName": "maintenanceEndDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "servers",
            "baseName": "servers",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "agents",
            "baseName": "agents",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "unlimitedAgents",
            "baseName": "unlimitedAgents",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "buildTypes",
            "baseName": "buildTypes",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "unlimitedBuildTypes",
            "baseName": "unlimitedBuildTypes",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "errorDetails",
            "baseName": "errorDetails",
            "type": "string",
            "format": ""
        },
        {
            "name": "key",
            "baseName": "key",
            "type": "string",
            "format": ""
        },
        {
            "name": "rawType",
            "baseName": "rawType",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LicenseKey.attributeTypeMap;
    }
    
    public constructor() {
    }
}

