/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { LicenseKeys } from './LicenseKeys.ts';
import { HttpFile } from '../http/http.ts';

export class LicensingData {
    'licenseUseExceeded'?: boolean;
    'maxAgents'?: number;
    'unlimitedAgents'?: boolean;
    'agentsLeft'?: number;
    'maxBuildTypes'?: number;
    'unlimitedBuildTypes'?: boolean;
    'buildTypesLeft'?: number;
    'serverLicenseType'?: string;
    'serverEffectiveReleaseDate'?: string;
    'licenseKeys'?: LicenseKeys;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "licenseUseExceeded",
            "baseName": "licenseUseExceeded",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "maxAgents",
            "baseName": "maxAgents",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "unlimitedAgents",
            "baseName": "unlimitedAgents",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "agentsLeft",
            "baseName": "agentsLeft",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "maxBuildTypes",
            "baseName": "maxBuildTypes",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "unlimitedBuildTypes",
            "baseName": "unlimitedBuildTypes",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "buildTypesLeft",
            "baseName": "buildTypesLeft",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "serverLicenseType",
            "baseName": "serverLicenseType",
            "type": "string",
            "format": ""
        },
        {
            "name": "serverEffectiveReleaseDate",
            "baseName": "serverEffectiveReleaseDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "licenseKeys",
            "baseName": "licenseKeys",
            "type": "LicenseKeys",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return LicensingData.attributeTypeMap;
    }
    
    public constructor() {
    }
}

