/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { MetricTags } from './MetricTags.ts';
import { MetricValues } from './MetricValues.ts';
import { HttpFile } from '../http/http.ts';

export class Metric {
    'name'?: string;
    'description'?: string;
    'prometheusName'?: string;
    'metricValues'?: MetricValues;
    'metricTags'?: MetricTags;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "prometheusName",
            "baseName": "prometheusName",
            "type": "string",
            "format": ""
        },
        {
            "name": "metricValues",
            "baseName": "metricValues",
            "type": "MetricValues",
            "format": ""
        },
        {
            "name": "metricTags",
            "baseName": "metricTags",
            "type": "MetricTags",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Metric.attributeTypeMap;
    }
    
    public constructor() {
    }
}

