/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { OperationResult } from './OperationResult.ts';
import { HttpFile } from '../http/http.ts';

export class MultipleOperationResult {
    'count'?: number;
    'errorCount'?: number;
    'operationResult'?: Array<OperationResult>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "errorCount",
            "baseName": "errorCount",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "operationResult",
            "baseName": "operationResult",
            "type": "Array<OperationResult>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return MultipleOperationResult.attributeTypeMap;
    }
    
    public constructor() {
    }
}

