/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RelatedEntity } from './RelatedEntity.ts';
import { HttpFile } from '../http/http.ts';

export class OperationResult {
    'message'?: string;
    'related'?: RelatedEntity;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "message",
            "baseName": "message",
            "type": "string",
            "format": ""
        },
        {
            "name": "related",
            "baseName": "related",
            "type": "RelatedEntity",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return OperationResult.attributeTypeMap;
    }
    
    public constructor() {
    }
}

