/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class ParsedTestName {
    'testPackage'?: string;
    'testSuite'?: string;
    'testClass'?: string;
    'testShortName'?: string;
    'testNameWithoutPrefix'?: string;
    'testMethodName'?: string;
    'testNameWithParameters'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "testPackage",
            "baseName": "testPackage",
            "type": "string",
            "format": ""
        },
        {
            "name": "testSuite",
            "baseName": "testSuite",
            "type": "string",
            "format": ""
        },
        {
            "name": "testClass",
            "baseName": "testClass",
            "type": "string",
            "format": ""
        },
        {
            "name": "testShortName",
            "baseName": "testShortName",
            "type": "string",
            "format": ""
        },
        {
            "name": "testNameWithoutPrefix",
            "baseName": "testNameWithoutPrefix",
            "type": "string",
            "format": ""
        },
        {
            "name": "testMethodName",
            "baseName": "testMethodName",
            "type": "string",
            "format": ""
        },
        {
            "name": "testNameWithParameters",
            "baseName": "testNameWithParameters",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ParsedTestName.attributeTypeMap;
    }
    
    public constructor() {
    }
}

