/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Permission } from './Permission.ts';
import { Project } from './Project.ts';
import { HttpFile } from '../http/http.ts';

export class PermissionAssignment {
    'permission'?: Permission;
    'project'?: Project;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "permission",
            "baseName": "permission",
            "type": "Permission",
            "format": ""
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "Project",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PermissionAssignment.attributeTypeMap;
    }
    
    public constructor() {
    }
}

