/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Problems } from './Problems.ts';
import { Tests } from './Tests.ts';
import { HttpFile } from '../http/http.ts';

export class ProblemTarget {
    'anyProblem'?: boolean;
    'tests'?: Tests;
    'problems'?: Problems;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "anyProblem",
            "baseName": "anyProblem",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "tests",
            "baseName": "tests",
            "type": "Tests",
            "format": ""
        },
        {
            "name": "problems",
            "baseName": "problems",
            "type": "Problems",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProblemTarget.attributeTypeMap;
    }
    
    public constructor() {
    }
}

