/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BuildType } from './BuildType.ts';
import { BuildTypes } from './BuildTypes.ts';
import { Project } from './Project.ts';
import { HttpFile } from '../http/http.ts';

export class ProblemScope {
    'project'?: Project;
    'buildTypes'?: BuildTypes;
    'buildType'?: BuildType;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "project",
            "baseName": "project",
            "type": "Project",
            "format": ""
        },
        {
            "name": "buildTypes",
            "baseName": "buildTypes",
            "type": "BuildTypes",
            "format": ""
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "BuildType",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProblemScope.attributeTypeMap;
    }
    
    public constructor() {
    }
}

