/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Build } from './Build.ts';
import { Mute } from './Mute.ts';
import { Problem } from './Problem.ts';
import { HttpFile } from '../http/http.ts';

export class ProblemOccurrence {
    'id'?: string;
    'type'?: string;
    'identity'?: string;
    'href'?: string;
    'muted'?: boolean;
    'currentlyInvestigated'?: boolean;
    'currentlyMuted'?: boolean;
    'logAnchor'?: string;
    'newFailure'?: boolean;
    'details'?: string;
    'additionalData'?: string;
    'problem'?: Problem;
    'mute'?: Mute;
    'build'?: Build;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "identity",
            "baseName": "identity",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "muted",
            "baseName": "muted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "currentlyInvestigated",
            "baseName": "currentlyInvestigated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "currentlyMuted",
            "baseName": "currentlyMuted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "logAnchor",
            "baseName": "logAnchor",
            "type": "string",
            "format": ""
        },
        {
            "name": "newFailure",
            "baseName": "newFailure",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string",
            "format": ""
        },
        {
            "name": "additionalData",
            "baseName": "additionalData",
            "type": "string",
            "format": ""
        },
        {
            "name": "problem",
            "baseName": "problem",
            "type": "Problem",
            "format": ""
        },
        {
            "name": "mute",
            "baseName": "mute",
            "type": "Mute",
            "format": ""
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "Build",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProblemOccurrence.attributeTypeMap;
    }
    
    public constructor() {
    }
}

