/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Investigations } from './Investigations.ts';
import { Mutes } from './Mutes.ts';
import { ProblemOccurrences } from './ProblemOccurrences.ts';
import { HttpFile } from '../http/http.ts';

export class Problem {
    'id'?: string;
    'type'?: string;
    'identity'?: string;
    'href'?: string;
    'description'?: string;
    'mutes'?: Mutes;
    'investigations'?: Investigations;
    'problemOccurrences'?: ProblemOccurrences;
    'locator'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "identity",
            "baseName": "identity",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "mutes",
            "baseName": "mutes",
            "type": "Mutes",
            "format": ""
        },
        {
            "name": "investigations",
            "baseName": "investigations",
            "type": "Investigations",
            "format": ""
        },
        {
            "name": "problemOccurrences",
            "baseName": "problemOccurrences",
            "type": "ProblemOccurrences",
            "format": ""
        },
        {
            "name": "locator",
            "baseName": "locator",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Problem.attributeTypeMap;
    }
    
    public constructor() {
    }
}

