/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Build } from './Build.ts';
import { HttpFile } from '../http/http.ts';

export class ProgressInfo {
    'percentageComplete'?: number;
    'elapsedSeconds'?: number;
    'estimatedTotalSeconds'?: number;
    'leftSeconds'?: number;
    'currentStageText'?: string;
    'outdated'?: boolean;
    'probablyHanging'?: boolean;
    'lastActivityTime'?: string;
    'outdatedReasonBuild'?: Build;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "percentageComplete",
            "baseName": "percentageComplete",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "elapsedSeconds",
            "baseName": "elapsedSeconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "estimatedTotalSeconds",
            "baseName": "estimatedTotalSeconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "leftSeconds",
            "baseName": "leftSeconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "currentStageText",
            "baseName": "currentStageText",
            "type": "string",
            "format": ""
        },
        {
            "name": "outdated",
            "baseName": "outdated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "probablyHanging",
            "baseName": "probablyHanging",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastActivityTime",
            "baseName": "lastActivityTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "outdatedReasonBuild",
            "baseName": "outdatedReasonBuild",
            "type": "Build",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProgressInfo.attributeTypeMap;
    }
    
    public constructor() {
    }
}

