/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class ProjectLocator {
    'affectedProject'?: string;
    'archived'?: boolean;
    'build'?: string;
    'buildType'?: string;
    'count'?: number;
    'defaultTemplate'?: string;
    'id'?: string;
    'internalId'?: string;
    'item'?: string;
    'name'?: string;
    'pool'?: string;
    'project'?: string;
    'projectFeature'?: string;
    'start'?: number;
    'uuid'?: string;
    'vcsRoot'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "affectedProject",
            "baseName": "affectedProject",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "archived",
            "baseName": "archived",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "string",
            "format": "BuildLocator"
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "string",
            "format": "BuildTypeLocator"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "defaultTemplate",
            "baseName": "defaultTemplate",
            "type": "string",
            "format": "BuildTypeLocator"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "internalId",
            "baseName": "internalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "string",
            "format": "item:(&lt;locator1&gt;),item:(&lt;locator2&gt;...)"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "pool",
            "baseName": "pool",
            "type": "string",
            "format": "AgentPoolLocator"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "projectFeature",
            "baseName": "projectFeature",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        },
        {
            "name": "vcsRoot",
            "baseName": "vcsRoot",
            "type": "string",
            "format": "VcsRootLocator"
        }    ];

    static getAttributeTypeMap() {
        return ProjectLocator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

