/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Builds } from './Builds.ts';
import { HttpFile } from '../http/http.ts';

export class Related {
    'builds'?: Builds;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "builds",
            "baseName": "builds",
            "type": "Builds",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Related.attributeTypeMap;
    }
    
    public constructor() {
    }
}

