/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { BranchVersion } from './BranchVersion.ts';
import { HttpFile } from '../http/http.ts';

export class RepositoryState {
    'timestamp'?: string;
    'count'?: number;
    'branch'?: Array<BranchVersion>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "timestamp",
            "baseName": "timestamp",
            "type": "string",
            "format": ""
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "branch",
            "baseName": "branch",
            "type": "Array<BranchVersion>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RepositoryState.attributeTypeMap;
    }
    
    public constructor() {
    }
}

