/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Href } from './Href.ts';
import { HttpFile } from '../http/http.ts';

export class Server {
    'version'?: string;
    'versionMajor'?: number;
    'versionMinor'?: number;
    'startTime'?: string;
    'currentTime'?: string;
    'buildNumber'?: string;
    'buildDate'?: string;
    'internalId'?: string;
    'role'?: string;
    'webUrl'?: string;
    'projects'?: Href;
    'vcsRoots'?: Href;
    'builds'?: Href;
    'users'?: Href;
    'userGroups'?: Href;
    'agents'?: Href;
    'buildQueue'?: Href;
    'agentPools'?: Href;
    'investigations'?: Href;
    'mutes'?: Href;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "version",
            "baseName": "version",
            "type": "string",
            "format": ""
        },
        {
            "name": "versionMajor",
            "baseName": "versionMajor",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "versionMinor",
            "baseName": "versionMinor",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "currentTime",
            "baseName": "currentTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildNumber",
            "baseName": "buildNumber",
            "type": "string",
            "format": ""
        },
        {
            "name": "buildDate",
            "baseName": "buildDate",
            "type": "string",
            "format": ""
        },
        {
            "name": "internalId",
            "baseName": "internalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": ""
        },
        {
            "name": "webUrl",
            "baseName": "webUrl",
            "type": "string",
            "format": ""
        },
        {
            "name": "projects",
            "baseName": "projects",
            "type": "Href",
            "format": ""
        },
        {
            "name": "vcsRoots",
            "baseName": "vcsRoots",
            "type": "Href",
            "format": ""
        },
        {
            "name": "builds",
            "baseName": "builds",
            "type": "Href",
            "format": ""
        },
        {
            "name": "users",
            "baseName": "users",
            "type": "Href",
            "format": ""
        },
        {
            "name": "userGroups",
            "baseName": "userGroups",
            "type": "Href",
            "format": ""
        },
        {
            "name": "agents",
            "baseName": "agents",
            "type": "Href",
            "format": ""
        },
        {
            "name": "buildQueue",
            "baseName": "buildQueue",
            "type": "Href",
            "format": ""
        },
        {
            "name": "agentPools",
            "baseName": "agentPools",
            "type": "Href",
            "format": ""
        },
        {
            "name": "investigations",
            "baseName": "investigations",
            "type": "Href",
            "format": ""
        },
        {
            "name": "mutes",
            "baseName": "mutes",
            "type": "Href",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Server.attributeTypeMap;
    }
    
    public constructor() {
    }
}

