/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Test } from './Test.ts';
import { TestCounters } from './TestCounters.ts';
import { HttpFile } from '../http/http.ts';

export class Tests {
    'count'?: number;
    'myTestCounters'?: TestCounters;
    'nextHref'?: string;
    'prevHref'?: string;
    'test'?: Array<Test>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "myTestCounters",
            "baseName": "myTestCounters",
            "type": "TestCounters",
            "format": ""
        },
        {
            "name": "nextHref",
            "baseName": "nextHref",
            "type": "string",
            "format": ""
        },
        {
            "name": "prevHref",
            "baseName": "prevHref",
            "type": "string",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "Array<Test>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Tests.attributeTypeMap;
    }
    
    public constructor() {
    }
}

