/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class TestOccurrenceLocator {
    'affectedProject'?: string;
    'branch'?: string;
    'build'?: string;
    'buildType'?: string;
    'count'?: number;
    'currentlyFailing'?: boolean;
    'currentlyInvestigated'?: boolean;
    'currentlyMuted'?: string;
    'id'?: number;
    'ignored'?: boolean;
    'includePersonal'?: boolean;
    'item'?: string;
    'lookupLimit'?: number;
    'muted'?: boolean;
    'name'?: string;
    'newFailure'?: string;
    'start'?: number;
    'status'?: string;
    'test'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "affectedProject",
            "baseName": "affectedProject",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "branch",
            "baseName": "branch",
            "type": "string",
            "format": ""
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "string",
            "format": "BuildLocator"
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "string",
            "format": "BuildTypeLocator"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "currentlyFailing",
            "baseName": "currentlyFailing",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "currentlyInvestigated",
            "baseName": "currentlyInvestigated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "currentlyMuted",
            "baseName": "currentlyMuted",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "ignored",
            "baseName": "ignored",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "includePersonal",
            "baseName": "includePersonal",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "string",
            "format": "item:(&lt;locator1&gt;),item:(&lt;locator2&gt;...)"
        },
        {
            "name": "lookupLimit",
            "baseName": "lookupLimit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "muted",
            "baseName": "muted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "newFailure",
            "baseName": "newFailure",
            "type": "string",
            "format": ""
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "string",
            "format": "TestLocator"
        }    ];

    static getAttributeTypeMap() {
        return TestOccurrenceLocator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

