/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Build } from './Build.ts';
import { Mute } from './Mute.ts';
import { Test } from './Test.ts';
import { TestOccurrences } from './TestOccurrences.ts';
import { TestRunMetadata } from './TestRunMetadata.ts';
import { HttpFile } from '../http/http.ts';

export class TestOccurrence {
    'id'?: string;
    'name'?: string;
    'status'?: string;
    'ignored'?: boolean;
    'duration'?: number;
    'runOrder'?: string;
    'newFailure'?: boolean;
    'muted'?: boolean;
    'currentlyMuted'?: boolean;
    'currentlyInvestigated'?: boolean;
    'href'?: string;
    'ignoreDetails'?: string;
    'details'?: string;
    'test'?: Test;
    'mute'?: Mute;
    'build'?: Build;
    'firstFailed'?: TestOccurrence;
    'nextFixed'?: TestOccurrence;
    'invocations'?: TestOccurrences;
    'metadata'?: TestRunMetadata;
    'logAnchor'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string",
            "format": ""
        },
        {
            "name": "ignored",
            "baseName": "ignored",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "duration",
            "baseName": "duration",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "runOrder",
            "baseName": "runOrder",
            "type": "string",
            "format": ""
        },
        {
            "name": "newFailure",
            "baseName": "newFailure",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "muted",
            "baseName": "muted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "currentlyMuted",
            "baseName": "currentlyMuted",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "currentlyInvestigated",
            "baseName": "currentlyInvestigated",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "ignoreDetails",
            "baseName": "ignoreDetails",
            "type": "string",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string",
            "format": ""
        },
        {
            "name": "test",
            "baseName": "test",
            "type": "Test",
            "format": ""
        },
        {
            "name": "mute",
            "baseName": "mute",
            "type": "Mute",
            "format": ""
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "Build",
            "format": ""
        },
        {
            "name": "firstFailed",
            "baseName": "firstFailed",
            "type": "TestOccurrence",
            "format": ""
        },
        {
            "name": "nextFixed",
            "baseName": "nextFixed",
            "type": "TestOccurrence",
            "format": ""
        },
        {
            "name": "invocations",
            "baseName": "invocations",
            "type": "TestOccurrences",
            "format": ""
        },
        {
            "name": "metadata",
            "baseName": "metadata",
            "type": "TestRunMetadata",
            "format": ""
        },
        {
            "name": "logAnchor",
            "baseName": "logAnchor",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TestOccurrence.attributeTypeMap;
    }
    
    public constructor() {
    }
}

