/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Investigations } from './Investigations.ts';
import { Mutes } from './Mutes.ts';
import { ParsedTestName } from './ParsedTestName.ts';
import { TestOccurrences } from './TestOccurrences.ts';
import { HttpFile } from '../http/http.ts';

export class Test {
    'id'?: string;
    'name'?: string;
    'mutes'?: Mutes;
    'investigations'?: Investigations;
    'testOccurrences'?: TestOccurrences;
    'parsedTestName'?: ParsedTestName;
    'href'?: string;
    'locator'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "mutes",
            "baseName": "mutes",
            "type": "Mutes",
            "format": ""
        },
        {
            "name": "investigations",
            "baseName": "investigations",
            "type": "Investigations",
            "format": ""
        },
        {
            "name": "testOccurrences",
            "baseName": "testOccurrences",
            "type": "TestOccurrences",
            "format": ""
        },
        {
            "name": "parsedTestName",
            "baseName": "parsedTestName",
            "type": "ParsedTestName",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "locator",
            "baseName": "locator",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Test.attributeTypeMap;
    }
    
    public constructor() {
    }
}

