/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Build } from './Build.ts';
import { BuildType } from './BuildType.ts';
import { Properties } from './Properties.ts';
import { User } from './User.ts';
import { HttpFile } from '../http/http.ts';

export class TriggeredBy {
    'type'?: string;
    'details'?: string;
    'date'?: string;
    'displayText'?: string;
    'rawValue'?: string;
    'user'?: User;
    'build'?: Build;
    'buildType'?: BuildType;
    'properties'?: Properties;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "details",
            "baseName": "details",
            "type": "string",
            "format": ""
        },
        {
            "name": "date",
            "baseName": "date",
            "type": "string",
            "format": ""
        },
        {
            "name": "displayText",
            "baseName": "displayText",
            "type": "string",
            "format": ""
        },
        {
            "name": "rawValue",
            "baseName": "rawValue",
            "type": "string",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "User",
            "format": ""
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "Build",
            "format": ""
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "BuildType",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Properties",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TriggeredBy.attributeTypeMap;
    }
    
    public constructor() {
    }
}

