/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class UserLocator {
    'affectedGroup'?: string;
    'email'?: string;
    'group'?: string;
    'id'?: string;
    'item'?: string;
    'lastLogin'?: Date;
    'name'?: string;
    'property'?: string;
    'role'?: string;
    'username'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "affectedGroup",
            "baseName": "affectedGroup",
            "type": "string",
            "format": "UserGroupLocator"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "group",
            "baseName": "group",
            "type": "string",
            "format": "UserGroupLocator"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "string",
            "format": "item:(&lt;locator1&gt;),item:(&lt;locator2&gt;...)"
        },
        {
            "name": "lastLogin",
            "baseName": "lastLogin",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string",
            "format": "property:(name:&lt;name&gt;,value:&lt;value&gt;,matchType:&lt;matchType&gt;)"
        },
        {
            "name": "role",
            "baseName": "role",
            "type": "string",
            "format": "RoleLocator"
        },
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return UserLocator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

