/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Groups } from './Groups.ts';
import { Properties } from './Properties.ts';
import { Roles } from './Roles.ts';
import { HttpFile } from '../http/http.ts';

export class User {
    'username'?: string;
    'name'?: string;
    'id'?: number;
    'email'?: string;
    'lastLogin'?: string;
    'password'?: string;
    'hasPassword'?: boolean;
    'realm'?: string;
    'href'?: string;
    'properties'?: Properties;
    'roles'?: Roles;
    'groups'?: Groups;
    'locator'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "username",
            "baseName": "username",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastLogin",
            "baseName": "lastLogin",
            "type": "string",
            "format": ""
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string",
            "format": ""
        },
        {
            "name": "hasPassword",
            "baseName": "hasPassword",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "realm",
            "baseName": "realm",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Properties",
            "format": ""
        },
        {
            "name": "roles",
            "baseName": "roles",
            "type": "Roles",
            "format": ""
        },
        {
            "name": "groups",
            "baseName": "groups",
            "type": "Groups",
            "format": ""
        },
        {
            "name": "locator",
            "baseName": "locator",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return User.attributeTypeMap;
    }
    
    public constructor() {
    }
}

