/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class VcsRootInstanceLocator {
    'affectedProject'?: string;
    'build'?: string;
    'buildType'?: string;
    'count'?: number;
    'id'?: number;
    'item'?: string;
    'lookupLimit'?: number;
    'project'?: string;
    'property'?: string;
    'start'?: number;
    'type'?: string;
    'vcsRoot'?: string;
    'versionedSettings'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "affectedProject",
            "baseName": "affectedProject",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "build",
            "baseName": "build",
            "type": "string",
            "format": "BuildLocator"
        },
        {
            "name": "buildType",
            "baseName": "buildType",
            "type": "string",
            "format": "BuildTypeLocator"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "string",
            "format": "item:(&lt;locator1&gt;),item:(&lt;locator2&gt;...)"
        },
        {
            "name": "lookupLimit",
            "baseName": "lookupLimit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string",
            "format": "property:(name:&lt;name&gt;,value:&lt;value&gt;,matchType:&lt;matchType&gt;)"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "vcsRoot",
            "baseName": "vcsRoot",
            "type": "string",
            "format": "VcsRootLocator"
        },
        {
            "name": "versionedSettings",
            "baseName": "versionedSettings",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VcsRootInstanceLocator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

