/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.ts';

export class VcsRootLocator {
    'affectedProject'?: string;
    'count'?: number;
    'id'?: number;
    'internalId'?: string;
    'item'?: string;
    'lookupLimit'?: number;
    'name'?: string;
    'project'?: string;
    'property'?: string;
    'start'?: number;
    'type'?: string;
    'uuid'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "affectedProject",
            "baseName": "affectedProject",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "count",
            "baseName": "count",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "internalId",
            "baseName": "internalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "item",
            "baseName": "item",
            "type": "string",
            "format": "item:(&lt;locator1&gt;),item:(&lt;locator2&gt;...)"
        },
        {
            "name": "lookupLimit",
            "baseName": "lookupLimit",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "project",
            "baseName": "project",
            "type": "string",
            "format": "ProjectLocator"
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string",
            "format": "property:(name:&lt;name&gt;,value:&lt;value&gt;,matchType:&lt;matchType&gt;)"
        },
        {
            "name": "start",
            "baseName": "start",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "string",
            "format": ""
        },
        {
            "name": "uuid",
            "baseName": "uuid",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VcsRootLocator.attributeTypeMap;
    }
    
    public constructor() {
    }
}

