/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VcsRoot } from './VcsRoot.ts';
import { HttpFile } from '../http/http.ts';

export class VcsRootEntry {
    'id'?: string;
    'inherited'?: boolean;
    'vcsRoot'?: VcsRoot;
    'checkoutRules'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "inherited",
            "baseName": "inherited",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "vcsRoot",
            "baseName": "vcs-root",
            "type": "VcsRoot",
            "format": ""
        },
        {
            "name": "checkoutRules",
            "baseName": "checkout-rules",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VcsRootEntry.attributeTypeMap;
    }
    
    public constructor() {
    }
}

