/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Items } from './Items.ts';
import { Properties } from './Properties.ts';
import { RepositoryState } from './RepositoryState.ts';
import { VcsRoot } from './VcsRoot.ts';
import { VcsStatus } from './VcsStatus.ts';
import { HttpFile } from '../http/http.ts';

export class VcsRootInstance {
    'id'?: string;
    'vcsRootId'?: string;
    'vcsRootInternalId'?: string;
    'name'?: string;
    'vcsName'?: string;
    'modificationCheckInterval'?: number;
    'commitHookMode'?: boolean;
    'lastVersion'?: string;
    'lastVersionInternal'?: string;
    'href'?: string;
    'vcsRoot'?: VcsRoot;
    'status'?: VcsStatus;
    'repositoryState'?: RepositoryState;
    'properties'?: Properties;
    'repositoryIdStrings'?: Items;
    'projectLocator'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "vcsRootId",
            "baseName": "vcs-root-id",
            "type": "string",
            "format": ""
        },
        {
            "name": "vcsRootInternalId",
            "baseName": "vcsRootInternalId",
            "type": "string",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "vcsName",
            "baseName": "vcsName",
            "type": "string",
            "format": ""
        },
        {
            "name": "modificationCheckInterval",
            "baseName": "modificationCheckInterval",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "commitHookMode",
            "baseName": "commitHookMode",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "lastVersion",
            "baseName": "lastVersion",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastVersionInternal",
            "baseName": "lastVersionInternal",
            "type": "string",
            "format": ""
        },
        {
            "name": "href",
            "baseName": "href",
            "type": "string",
            "format": ""
        },
        {
            "name": "vcsRoot",
            "baseName": "vcs-root",
            "type": "VcsRoot",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "VcsStatus",
            "format": ""
        },
        {
            "name": "repositoryState",
            "baseName": "repositoryState",
            "type": "RepositoryState",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "Properties",
            "format": ""
        },
        {
            "name": "repositoryIdStrings",
            "baseName": "repositoryIdStrings",
            "type": "Items",
            "format": ""
        },
        {
            "name": "projectLocator",
            "baseName": "projectLocator",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VcsRootInstance.attributeTypeMap;
    }
    
    public constructor() {
    }
}

