/**
 * TeamCity REST API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 2018.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { VcsCheckStatus } from './VcsCheckStatus.ts';
import { HttpFile } from '../http/http.ts';

export class VcsStatus {
    'current'?: VcsCheckStatus;
    'previous'?: VcsCheckStatus;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "current",
            "baseName": "current",
            "type": "VcsCheckStatus",
            "format": ""
        },
        {
            "name": "previous",
            "baseName": "previous",
            "type": "VcsCheckStatus",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return VcsStatus.attributeTypeMap;
    }
    
    public constructor() {
    }
}

